name:                venge
version:             0.1.0.0
github:              "JackAllTrades-MoN/venge"
license:             BSD3
author:              "Jack AT"
maintainer:          "magikku009@hotmail.co.jp"
copyright:           "Copyright (c) 2020 Jack AllTrades"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JackAllTrades-MoN/venge#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative
- sdl2
- sdl2-ttf
- sdl2-image
- text
- containers
- array
- mtl
- process

library:
  source-dirs: src

executables:
  venge-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - venge

tests:
  venge-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - venge
